import {Book, Category, CartItem, User, UserRole, Order, OrderStatus} from '../models/models';

export const MOCK_BOOKS: Book[] = [
  {
    id: '1',
    title: 'Clean Code',
    author: 'Robert C. Martin',
    description:
      "A Handbook of Agile Software Craftsmanship. Even bad code can function. But if code isn't clean, it can bring a development organization to its knees.",
    price: 34.99,
    availability: true,
    stock: 25,
    category: 'Technology',
    genre: ['Software Development', 'Programming'],
    isbn: '9780132350884',
    rating: 4.7,
    reviews: [
      {
        id: 'r1',
        userId: 'u2',
        userName: 'Jane Smith',
        bookId: '1',
        rating: 5,
        comment: 'A must-read for every developer.',
        date: new Date('2025-11-15'),
      },
    ],
    imageUrl: 'https://picsum.photos/seed/1/200/300',
    createdAt: new Date('2025-10-01'),
  },
  {
    id: '2',
    title: 'The Great Gatsby',
    author: 'F. Scott Fitzgerald',
    description:
      'The story of the mysteriously wealthy Jay Gatsby and his love for the beautiful Daisy Buchanan.',
    price: 12.99,
    availability: true,
    stock: 50,
    category: 'Fiction',
    genre: ['Classic', 'Literary Fiction'],
    isbn: '9780743273565',
    rating: 4.4,
    reviews: [],
    imageUrl: 'https://picsum.photos/seed/2/200/300',
    createdAt: new Date('2025-09-15'),
  },
  {
    id: '3',
    title: 'Sapiens: A Brief History of Humankind',
    author: 'Yuval Noah Harari',
    description:
      "A groundbreaking narrative of humanity's creation and evolution that explores how biology and history have defined what it means to be human.",
    price: 18.99,
    availability: true,
    stock: 30,
    category: 'Non-fiction',
    genre: ['History', 'Anthropology'],
    isbn: '9780062316097',
    rating: 4.6,
    reviews: [],
    imageUrl: 'https://picsum.photos/seed/3/200/300',
    createdAt: new Date('2025-08-20'),
  },
  {
    id: '4',
    title: 'Design Patterns',
    author: 'Gang of Four',
    description:
      'Elements of Reusable Object-Oriented Software. Capturing a wealth of experience about the design of object-oriented software.',
    price: 44.99,
    availability: false,
    stock: 0,
    category: 'Technology',
    genre: ['Software Development', 'Programming'],
    isbn: '9780201633610',
    rating: 4.3,
    reviews: [],
    imageUrl: 'https://picsum.photos/seed/4/200/300',
    createdAt: new Date('2025-07-10'),
  },
  {
    id: '5',
    title: "Harry Potter and the Philosopher's Stone",
    author: 'J.K. Rowling',
    description: 'The first book in the beloved Harry Potter series about a young wizard.',
    price: 14.99,
    availability: true,
    stock: 100,
    category: 'Kids',
    genre: ['Fantasy'],
    isbn: '9780747532699',
    rating: 4.9,
    reviews: [],
    imageUrl: 'https://picsum.photos/seed/5/200/300',
    createdAt: new Date('2025-06-01'),
  },
  {
    id: '6',
    title: '1984',
    author: 'George Orwell',
    description: 'A dystopian novel set in a totalitarian society ruled by Big Brother.',
    price: 11.99,
    availability: true,
    stock: 40,
    category: 'Fiction',
    genre: ['Classic', 'Dystopian'],
    isbn: '9780451524935',
    rating: 4.8,
    reviews: [],
    imageUrl: 'https://picsum.photos/seed/6/200/300',
    createdAt: new Date('2025-05-15'),
  },
];

export const MOCK_CATEGORIES: Category[] = [
  {id: 'cat-1', name: 'Fiction', description: 'Fiction books', bookCount: 167},
  {id: 'cat-2', name: 'Non-fiction', description: 'Non-fiction books', bookCount: 142},
  {id: 'cat-3', name: 'Technology', description: 'Technology books', bookCount: 198},
  {id: 'cat-4', name: 'Science', description: 'Science books', bookCount: 156},
  {id: 'cat-5', name: 'Kids', description: 'Children books', bookCount: 189},
  {id: 'cat-6', name: 'Education', description: 'Educational books', bookCount: 148},
];

export const MOCK_CART_ITEMS: CartItem[] = [
  {
    id: 'ci-1',
    bookId: '1',
    bookTitle: 'Clean Code',
    bookPrice: 34.99,
    quantity: 1,
    imageUrl: 'https://picsum.photos/seed/1/200/300',
  },
  {
    id: 'ci-2',
    bookId: '2',
    bookTitle: 'The Great Gatsby',
    bookPrice: 12.99,
    quantity: 2,
    imageUrl: 'https://picsum.photos/seed/2/200/300',
  },
];

export const MOCK_USER: User = {
  id: 'u1',
  name: 'John Doe',
  email: 'john@example.com',
  role: UserRole.USER,
  addresses: [
    {
      id: 'a1',
      street: '123 Main St',
      city: 'Reading',
      state: 'PA',
      zipCode: '19601',
      country: 'USA',
      isDefault: true,
    },
  ],
  orderHistoryIds: ['o1'],
  wishlistIds: ['2'],
};

export const MOCK_ORDERS: Order[] = [
  {
    id: 'ORD-ABC12345',
    userId: 'u1',
    items: [MOCK_CART_ITEMS[0]],
    total: 34.99,
    shippingAddress: MOCK_USER.addresses[0],
    paymentMethod: 'Credit Card',
    status: OrderStatus.DELIVERED,
    orderDate: new Date('2025-12-01'),
    trackingNumber: 'TRK-123456',
  },
  {
    id: 'ORD-DEF67890',
    userId: 'u1',
    items: MOCK_CART_ITEMS,
    total: 60.97,
    shippingAddress: MOCK_USER.addresses[0],
    paymentMethod: 'PayPal',
    status: OrderStatus.SHIPPED,
    orderDate: new Date('2026-01-15'),
    trackingNumber: 'TRK-789012',
  },
];
